---
name: books_app
description: A new Flutter project.
publish_to: none
version: 0.0.6+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  package_info_plus: ^8.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_lints: ^3.0.0
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: web/icons/books.png
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/

    
    # Package rename config
package_rename_config:
  windows:
    app_name: "Book App"
  